FROM node

RUN npm install react react-panorama
RUN npm install -D webpack@latest webpack-cli webpack-panorama
RUN npm install -D typescript ts-loader fork-ts-checker-webpack-plugin
RUN npm install panorama-types
